plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/ubuntu/clawd/projects/client-acquisition/demos/counselling-in-the-community"
publishOrigin = "default"
base = "/home/ubuntu/clawd/projects/client-acquisition/demos/counselling-in-the-community"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]